version: '3'

services:
  # MYSQL service
  mysql:
    build:
      context: ./mysql-dockerfile
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes: 
      - mysql_volume:/var/lib/mysql

  # Wordpress service
  wordpress:
    depends_on:
      - mysql
    build:
      context: ./wordpress-dockerfile
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - wordpress_volume:/var/www/html

volumes:
  mysql_volume: {}
  wordpress_volume: {}
