version: '3'

services:
  # MYSQL service
  mysql:
    build:
      context: ./mysql-dockerfile
    container_name: mysql_container
    networks:
      - wpsite
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: userdb
      MYSQL_PASSWORD: passworddb
      MYSQL_DATABASE: wordpress_db
    volumes: 
      - mysql_volume:/var/lib/mysql

  # Wordpress service
  wordpress:
    depends_on:
      - mysql
    build:
      context: ./wordpress-dockerfile
    container_name: wordpress_container
    restart: always
    environment:
         - WORDPRESS_DB_HOST=localhost:3306
         - WORDPRESS_DB_USER=userdb
         - WORDPRESS_DB_PASSWORD=passworddb
         - WORDPRESS_DB_NAME=wordpress_db
    ports:
      - "80:80"
    volumes:
      - wordpress_volume:/var/www/html

networks:
  wpsite:

volumes:
  mysql_volume: {}
  wordpress_volume: {}
